# Generated by Django 4.2.5 on 2023-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.IntegerField(default=0, verbose_name='Takip'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.IntegerField(default=0, verbose_name='Takipçi'),
        ),
    ]
