# Generated by Django 4.2.5 on 2023-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userprofile_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers_count',
            field=models.IntegerField(default=5),
        ),
    ]
